"""db/sql_registry.py

Central SQL registry.  Every query type uses %s placeholders — no values
are hardcoded.  Parameter order per ranking type:

  top / bottom              (start_date, end_date, limit::int)
  aggregate                 (start_date, end_date)
  threshold-absolute        (start_date, end_date, threshold_value::numeric)
  threshold-percentage      generated by LLM (Qwen) — 4 params usually
                            (start, end, start, end) via subquery
  zero_filter               (start_date, end_date)
"""

SQL_REGISTRY = {

    # ──────────────────────────────────────────────────────────────────────────
    "product": {
        "revenue": {
            "top": """
                SELECT p.product_name AS name,
                       SUM(oi.quantity * oi.item_price) AS value
                FROM order_items oi
                JOIN orders o ON oi.order_id = o.order_id
                JOIN products p ON oi.product_id = p.product_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY p.product_name
                ORDER BY value DESC
                LIMIT %s;
            """,
            "bottom": """
                SELECT p.product_name AS name,
                       SUM(oi.quantity * oi.item_price) AS value
                FROM order_items oi
                JOIN orders o ON oi.order_id = o.order_id
                JOIN products p ON oi.product_id = p.product_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY p.product_name
                ORDER BY value ASC
                LIMIT %s;
            """,
            "aggregate": """
                SELECT SUM(oi.quantity * oi.item_price) AS value
                FROM order_items oi
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s;
            """,
            # Absolute threshold: HAVING SUM(...) > threshold_value
            # Params: (start_date, end_date, threshold_value)
            "threshold_absolute": """
                SELECT p.product_name AS name,
                       SUM(oi.quantity * oi.item_price) AS value
                FROM order_items oi
                JOIN orders o ON oi.order_id = o.order_id
                JOIN products p ON oi.product_id = p.product_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY p.product_name
                HAVING SUM(oi.quantity * oi.item_price) > %s
                ORDER BY value DESC;
            """,
            "threshold_percentage_tmpl": """
                SELECT p.product_name AS name,
                       SUM(oi.quantity * oi.item_price) AS value
                FROM order_items oi
                JOIN orders o ON oi.order_id = o.order_id
                JOIN products p ON oi.product_id = p.product_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY p.product_name
                HAVING SUM(oi.quantity * oi.item_price) > {pct} * (
                    SELECT SUM(oi2.quantity * oi2.item_price)
                    FROM order_items oi2
                    JOIN orders o2 ON oi2.order_id = o2.order_id
                    WHERE o2.order_date BETWEEN %s AND %s
                )
                ORDER BY value DESC;
            """,
            # Zero filter: products with NO revenue in the period
            "zero_filter": """
                SELECT p.product_name AS name, 0 AS value
                FROM products p
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM order_items oi
                    JOIN orders o ON oi.order_id = o.order_id
                    WHERE oi.product_id = p.product_id
                      AND o.order_date BETWEEN %s AND %s
                )
                ORDER BY p.product_name;
            """,
        },

        "quantity": {
            "top": """
                SELECT p.product_name AS name,
                       SUM(oi.quantity) AS value
                FROM order_items oi
                JOIN orders o ON oi.order_id = o.order_id
                JOIN products p ON oi.product_id = p.product_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY p.product_name
                ORDER BY value DESC
                LIMIT %s;
            """,
            "bottom": """
                SELECT p.product_name AS name,
                       SUM(oi.quantity) AS value
                FROM order_items oi
                JOIN orders o ON oi.order_id = o.order_id
                JOIN products p ON oi.product_id = p.product_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY p.product_name
                ORDER BY value ASC
                LIMIT %s;
            """,
            "aggregate": """
                SELECT SUM(oi.quantity) AS value
                FROM order_items oi
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s;
            """,
            # Absolute threshold: HAVING SUM(quantity) > threshold_value
            # Params: (start_date, end_date, threshold_value)
            "threshold_absolute": """
                SELECT p.product_name AS name,
                       SUM(oi.quantity) AS value
                FROM order_items oi
                JOIN orders o ON oi.order_id = o.order_id
                JOIN products p ON oi.product_id = p.product_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY p.product_name
                HAVING SUM(oi.quantity) > %s
                ORDER BY value DESC;
            """,
            "threshold_percentage_tmpl": """
                SELECT p.product_name AS name,
                       SUM(oi.quantity) AS value
                FROM order_items oi
                JOIN orders o ON oi.order_id = o.order_id
                JOIN products p ON oi.product_id = p.product_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY p.product_name
                HAVING SUM(oi.quantity) > {pct} * (
                    SELECT SUM(oi2.quantity)
                    FROM order_items oi2
                    JOIN orders o2 ON oi2.order_id = o2.order_id
                    WHERE o2.order_date BETWEEN %s AND %s
                )
                ORDER BY value DESC;
            """,
            # Zero filter: products with NO units sold in the period
            "zero_filter": """
                SELECT p.product_name AS name, 0 AS value
                FROM products p
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM order_items oi
                    JOIN orders o ON oi.order_id = o.order_id
                    WHERE oi.product_id = p.product_id
                      AND o.order_date BETWEEN %s AND %s
                )
                ORDER BY p.product_name;
            """,
        },
    },

    # ──────────────────────────────────────────────────────────────────────────
    "customer": {
        "revenue": {
            "top": """
                SELECT c.customer_name AS name,
                       SUM(o.total_amount) AS value
                FROM orders o
                JOIN customers c ON o.customer_id = c.customer_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY c.customer_name
                ORDER BY value DESC
                LIMIT %s;
            """,
            "bottom": """
                SELECT c.customer_name AS name,
                       SUM(o.total_amount) AS value
                FROM orders o
                JOIN customers c ON o.customer_id = c.customer_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY c.customer_name
                ORDER BY value ASC
                LIMIT %s;
            """,
            "aggregate": """
                SELECT SUM(o.total_amount) AS value
                FROM orders o
                WHERE o.order_date BETWEEN %s AND %s;
            """,
            "threshold_absolute": """
                SELECT c.customer_name AS name,
                       SUM(o.total_amount) AS value
                FROM orders o
                JOIN customers c ON o.customer_id = c.customer_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY c.customer_name
                HAVING SUM(o.total_amount) > %s
                ORDER BY value DESC;
            """,
            "threshold_percentage_tmpl": """
                SELECT c.customer_name AS name,
                       SUM(o.total_amount) AS value
                FROM orders o
                JOIN customers c ON o.customer_id = c.customer_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY c.customer_name
                HAVING SUM(o.total_amount) > {pct} * (
                    SELECT SUM(o2.total_amount)
                    FROM orders o2
                    WHERE o2.order_date BETWEEN %s AND %s
                )
                ORDER BY value DESC;
            """,
            "zero_filter": """
                SELECT c.customer_name AS name, 0 AS value
                FROM customers c
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM orders o
                    WHERE o.customer_id = c.customer_id
                      AND o.order_date BETWEEN %s AND %s
                )
                ORDER BY c.customer_name;
            """,
        },
    },

    # ──────────────────────────────────────────────────────────────────────────
    "city": {
        "revenue": {
            "top": """
                SELECT ci.city_name AS name,
                       SUM(o.total_amount) AS value
                FROM orders o
                JOIN customers cu ON o.customer_id = cu.customer_id
                JOIN cities ci ON cu.city_id = ci.city_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY ci.city_name
                ORDER BY value DESC
                LIMIT %s;
            """,
            "bottom": """
                SELECT ci.city_name AS name,
                       SUM(o.total_amount) AS value
                FROM orders o
                JOIN customers cu ON o.customer_id = cu.customer_id
                JOIN cities ci ON cu.city_id = ci.city_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY ci.city_name
                ORDER BY value ASC
                LIMIT %s;
            """,
            "aggregate": """
                SELECT SUM(o.total_amount) AS value
                FROM orders o
                JOIN customers cu ON o.customer_id = cu.customer_id
                JOIN cities ci ON cu.city_id = ci.city_id
                WHERE o.order_date BETWEEN %s AND %s;
            """,
            "threshold_absolute": """
                SELECT ci.city_name AS name,
                       SUM(o.total_amount) AS value
                FROM orders o
                JOIN customers cu ON o.customer_id = cu.customer_id
                JOIN cities ci ON cu.city_id = ci.city_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY ci.city_name
                HAVING SUM(o.total_amount) > %s
                ORDER BY value DESC;
            """,
            "threshold_percentage_tmpl": """
                SELECT ci.city_name AS name,
                       SUM(o.total_amount) AS value
                FROM orders o
                JOIN customers cu ON o.customer_id = cu.customer_id
                JOIN cities ci ON cu.city_id = ci.city_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY ci.city_name
                HAVING SUM(o.total_amount) > {pct} * (
                    SELECT SUM(o2.total_amount)
                    FROM orders o2
                    WHERE o2.order_date BETWEEN %s AND %s
                )
                ORDER BY value DESC;
            """,
            "zero_filter": """
                SELECT ci.city_name AS name, 0 AS value
                FROM cities ci
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM orders o
                    JOIN customers cu ON o.customer_id = cu.customer_id
                    WHERE cu.city_id = ci.city_id
                      AND o.order_date BETWEEN %s AND %s
                )
                ORDER BY ci.city_name;
            """,
        },
    },

    # ──────────────────────────────────────────────────────────────────────────
    "category": {
        "revenue": {
            "top": """
                SELECT cat.category_name AS name,
                       SUM(oi.quantity * oi.item_price) AS value
                FROM order_items oi
                JOIN products p ON oi.product_id = p.product_id
                JOIN categories cat ON p.category_id = cat.category_id
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY cat.category_name
                ORDER BY value DESC
                LIMIT %s;
            """,
            "bottom": """
                SELECT cat.category_name AS name,
                       SUM(oi.quantity * oi.item_price) AS value
                FROM order_items oi
                JOIN products p ON oi.product_id = p.product_id
                JOIN categories cat ON p.category_id = cat.category_id
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY cat.category_name
                ORDER BY value ASC
                LIMIT %s;
            """,
            "aggregate": """
                SELECT SUM(oi.quantity * oi.item_price) AS value
                FROM order_items oi
                JOIN products p ON oi.product_id = p.product_id
                JOIN categories cat ON p.category_id = cat.category_id
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s;
            """,
            "threshold_absolute": """
                SELECT cat.category_name AS name,
                       SUM(oi.quantity * oi.item_price) AS value
                FROM order_items oi
                JOIN products p ON oi.product_id = p.product_id
                JOIN categories cat ON p.category_id = cat.category_id
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY cat.category_name
                HAVING SUM(oi.quantity * oi.item_price) > %s
                ORDER BY value DESC;
            """,
            "threshold_percentage_tmpl": """
                SELECT cat.category_name AS name,
                       SUM(oi.quantity * oi.item_price) AS value
                FROM order_items oi
                JOIN products p ON oi.product_id = p.product_id
                JOIN categories cat ON p.category_id = cat.category_id
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY cat.category_name
                HAVING SUM(oi.quantity * oi.item_price) > {pct} * (
                    SELECT SUM(oi2.quantity * oi2.item_price)
                    FROM order_items oi2
                    JOIN orders o2 ON oi2.order_id = o2.order_id
                    WHERE o2.order_date BETWEEN %s AND %s
                )
                ORDER BY value DESC;
            """,
            "zero_filter": """
                SELECT cat.category_name AS name, 0 AS value
                FROM categories cat
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM order_items oi
                    JOIN products p ON oi.product_id = p.product_id
                    JOIN orders o ON oi.order_id = o.order_id
                    WHERE p.category_id = cat.category_id
                      AND o.order_date BETWEEN %s AND %s
                )
                ORDER BY cat.category_name;
            """,
        },

        "quantity": {
            "top": """
                SELECT cat.category_name AS name,
                       SUM(oi.quantity) AS value
                FROM order_items oi
                JOIN products p ON oi.product_id = p.product_id
                JOIN categories cat ON p.category_id = cat.category_id
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY cat.category_name
                ORDER BY value DESC
                LIMIT %s;
            """,
            "bottom": """
                SELECT cat.category_name AS name,
                       SUM(oi.quantity) AS value
                FROM order_items oi
                JOIN products p ON oi.product_id = p.product_id
                JOIN categories cat ON p.category_id = cat.category_id
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY cat.category_name
                ORDER BY value ASC
                LIMIT %s;
            """,
            "aggregate": """
                SELECT SUM(oi.quantity) AS value
                FROM order_items oi
                JOIN products p ON oi.product_id = p.product_id
                JOIN categories cat ON p.category_id = cat.category_id
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s;
            """,
            "threshold_absolute": """
                SELECT cat.category_name AS name,
                       SUM(oi.quantity) AS value
                FROM order_items oi
                JOIN products p ON oi.product_id = p.product_id
                JOIN categories cat ON p.category_id = cat.category_id
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY cat.category_name
                HAVING SUM(oi.quantity) > %s
                ORDER BY value DESC;
            """,
            "threshold_percentage_tmpl": """
                SELECT cat.category_name AS name,
                       SUM(oi.quantity) AS value
                FROM order_items oi
                JOIN products p ON oi.product_id = p.product_id
                JOIN categories cat ON p.category_id = cat.category_id
                JOIN orders o ON oi.order_id = o.order_id
                WHERE o.order_date BETWEEN %s AND %s
                GROUP BY cat.category_name
                HAVING SUM(oi.quantity) > {pct} * (
                    SELECT SUM(oi2.quantity)
                    FROM order_items oi2
                    JOIN orders o2 ON oi2.order_id = o2.order_id
                    WHERE o2.order_date BETWEEN %s AND %s
                )
                ORDER BY value DESC;
            """,
            "zero_filter": """
                SELECT cat.category_name AS name, 0 AS value
                FROM categories cat
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM order_items oi
                    JOIN products p ON oi.product_id = p.product_id
                    JOIN orders o ON oi.order_id = o.order_id
                    WHERE p.category_id = cat.category_id
                      AND o.order_date BETWEEN %s AND %s
                )
                ORDER BY cat.category_name;
            """,
        },
    },
}