"""Step 5: Execute Query — runs LLM-generated SQL against PostgreSQL.

This step is intentionally thin: no special-case routing for growth/intersection/
zero_filter/threshold. All that logic is in the SQL generated by LLaMA.

Param building is the only Python logic: count %s placeholders and
fill them from the structured intent (dates + optional limit/threshold).
"""

import os, sys, calendar

_STEPS_DIR    = os.path.dirname(os.path.abspath(__file__))
_MOTIA_DIR    = os.path.dirname(_STEPS_DIR)
_PROJECT_ROOT = os.path.dirname(_MOTIA_DIR)
for _p in [_STEPS_DIR, _MOTIA_DIR, _PROJECT_ROOT]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

import psycopg2
from datetime import date
from typing import Any
from motia import FlowContext, queue
from shared_config import POSTGRES

config = {
    "name": "ExecuteQuery",
    "description": "Executes LLM-generated SQL. Param building only — no query-type routing.",
    "flows": ["sales-analytics-flow"],
    "triggers": [queue("query::execute")],
    "enqueues": ["query::format.result"],
}


def _run_sql(sql: str, params: tuple):
    conn = psycopg2.connect(**POSTGRES)
    cur  = conn.cursor()
    cur.execute(sql, params)
    rows = cur.fetchall()
    cur.close()
    conn.close()
    return rows


def _rows_to_dicts(rows: list) -> list[dict]:
    """Convert raw rows → list of dicts based on column count."""
    result = []
    for row in rows:
        if len(row) == 1:
            result.append({"value": float(row[0]) if row[0] is not None else None})
        elif len(row) == 2:
            result.append({"name": str(row[0]),
                            "value": float(row[1]) if row[1] is not None else 0.0})
        elif len(row) == 3:
            result.append({"name": str(row[0]),
                            "value1": float(row[1]) if row[1] is not None else 0.0,
                            "value2": float(row[2]) if row[2] is not None else 0.0})
        elif len(row) >= 4:
            result.append({"name":   str(row[0]),
                            "value1": float(row[1]) if row[1] is not None else 0.0,
                            "value2": float(row[2]) if row[2] is not None else 0.0,
                            "delta":  float(row[3]) if row[3] is not None else 0.0})
    return result


def _build_params(sql: str, parsed: dict) -> tuple:
    """
    Fill %s placeholders from the parsed intent.

    Placeholder count convention (what LLaMA is prompted to produce):
      top_n / bottom_n     : (start, end, limit)                  → 3 params
      aggregate / zero     : (start, end)                         → 2 params
      threshold absolute   : (start, end, threshold_value)        → 3 params
      threshold percentage : (start, end, start, end)             → 4 params
      comparison / growth  : (start1, end1, start2, end2, limit)  → 5 params
      intersection         : varies (up to 9) — fill date pairs first, limit last
    """
    n    = sql.count("%s")
    trs  = parsed.get("time_ranges", [])
    qt   = parsed.get("query_type", "top_n")
    top_n= parsed.get("top_n", 5) or 5
    thr  = parsed.get("threshold")

    if n == 0:
        return ()

    # Parse date strings to date objects
    def _d(s: str) -> date:
        return date.fromisoformat(s)

    # Two-period queries
    if qt in ("comparison", "growth_ranking", "intersection") and len(trs) >= 2:
        s1, e1 = _d(trs[0]["start"]), _d(trs[0]["end"])
        s2, e2 = _d(trs[1]["start"]), _d(trs[1]["end"])
        if n == 4:
            return (s1, e1, s2, e2)
        if n == 5:
            return (s1, e1, s2, e2, top_n)
        # More params (intersection may have repeated dates)
        base = [s1, e1, s2, e2]
        while len(base) < n - 1:
            base += [s1, e1]
        if n > len(base):
            base.append(top_n)
        return tuple(base[:n])

    # Single-period queries
    if trs:
        s, e = _d(trs[0]["start"]), _d(trs[0]["end"])
    else:
        # No time range in intent — this should not happen if Qwen parsed correctly.
        # Use current year as a safe non-hardcoded fallback.
        today = date.today()
        s, e  = today.replace(month=1, day=1), today.replace(month=12, day=31)

    if n == 2:
        return (s, e)
    if n == 3:
        if qt == "threshold" and thr and thr.get("type") == "absolute":
            return (s, e, thr["value"])
        return (s, e, top_n)
    if n == 4 and qt == "threshold":
        # percentage template: (start, end, start, end)
        return (s, e, s, e)
    if n == 5 and qt == "threshold" and thr and thr.get("type") == "percentage":
        # builder percentage SQL: (start, end, pct_value, start, end)
        return (s, e, thr["value"], s, e)

    # Generic: fill date pairs, last slot = limit or threshold
    slots: list = []
    for i in range(n):
        if i == n - 1:
            if qt == "threshold" and thr and thr.get("type") == "absolute":
                slots.append(thr["value"])
            else:
                slots.append(top_n)
        elif i % 2 == 0:
            slots.append(s)
        else:
            slots.append(e)
    return tuple(slots)


def _period_label(start_str: str, end_str: str) -> str:
    s = date.fromisoformat(start_str)
    e = date.fromisoformat(end_str)
    if s.month == e.month and s.year == e.year:
        return f"{calendar.month_name[s.month]} {s.year}"
    if s.day == 1 and e.day >= 28:
        return f"{calendar.month_abbr[s.month]}–{calendar.month_abbr[e.month]} {s.year}"
    return f"{s} to {e}"


async def _error(ctx, qs, query_id, msg):
    if qs:
        await ctx.state.set("queries", query_id, {**qs, "status": "error", "error": msg})


async def handler(input_data: Any, ctx: FlowContext[Any]) -> None:
    query_id      = input_data.get("queryId")
    user_query    = input_data.get("query", "")
    parsed        = input_data.get("parsed", {})
    generated_sql = input_data.get("generated_sql")

    if not generated_sql:
        qs = await ctx.state.get("queries", query_id)
        await _error(ctx, qs, query_id, "No SQL was generated.")
        return

    qt   = parsed.get("query_type", "top_n")
    trs  = parsed.get("time_ranges", [])

    ctx.logger.info("🗄️ Executing SQL", {"queryId": query_id, "query_type": qt})

    try:
        params = _build_params(generated_sql, parsed)
        rows   = _run_sql(generated_sql, params)
        results = _rows_to_dicts(rows)
        ctx.logger.info("✅ SQL executed", {"queryId": query_id, "rows": len(results)})
    except Exception as exc:
        qs = await ctx.state.get("queries", query_id)
        await _error(ctx, qs, query_id, f"SQL execution failed: {exc}")
        return

    # Guard: growth_ranking with all-zero period2 = no data (e.g. Q4 beyond dataset)
    if qt == "growth_ranking" and results:
        all_zero_p2 = all(r.get("value2", 0) == 0 for r in results)
        all_zero_p1 = all(r.get("value1", 0) == 0 for r in results)
        trs = parsed.get("time_ranges", [])
        if all_zero_p2 and not all_zero_p1 and len(trs) >= 2:
            qs = await ctx.state.get("queries", query_id)
            end_p2 = trs[1]["end"] if len(trs) > 1 else "unknown"
            await _error(ctx, qs, query_id,
                f"No data found for the second period (ending {end_p2}). "
                "The dataset may not cover this time range.")
            return

    # Shape validation: detect LLM returning wrong query structure
    _RANKED_TYPES = {"top_n","bottom_n","threshold","intersection","zero_filter","growth_ranking","comparison"}
    if qt in _RANKED_TYPES:
        # These must return named rows, not a scalar
        if results and "name" not in results[0]:
            qs = await ctx.state.get("queries", query_id)
            await _error(ctx, qs, query_id,
                f"SQL returned a scalar total instead of per-entity rows "
                f"for query_type={qt}. The SQL was likely incorrect."
            )
            return

    qs = await ctx.state.get("queries", query_id)
    if qs:
        await ctx.state.set("queries", query_id, {**qs, "status": "executed", "results": results})

    # Build period labels for formatting
    period_labels = [_period_label(t["start"], t["end"]) for t in trs]
    start_date = trs[0]["start"] if trs else ""
    end_date   = trs[-1]["end"]  if trs else ""

    await ctx.enqueue({"topic": "query::format.result", "data": {
        "queryId":       query_id,
        "query":         user_query,
        "parsed":        parsed,
        "results":       results,
        "period_labels": period_labels,
        "startDate":     start_date,
        "endDate":       end_date,
    }})